### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by Shardj** [CodeSnippetHQ/tutorial-openai-chat-api#1]
This seems to use completions and not chat completions, so it surely won't work in the way you're saying it will. Each prompt you give to OpenAI will be standalone without the context of previous messages and responses.

**Comment by timmywheels** [comment]
@Shardj you're right -- updating the project and my blog post shortly. Thanks for calling this out 🙌

**Comment by timmywheels** [comment]
Here's the PR, will merge it in when I get a second to update the blog post accordingly: https://github.com/CodeSnippetHQ/tutorial-openai-completions-api/pull/2

**Comment by Shardj** [comment]
Looks good, glad I could help

**Comment by timmywheels** [comment]
changes have been merged, thanks again!
